In [412]:
import pandas as pd
import numpy as np
import time

In [2]:
import folium

In [349]:
from folium import plugins

In [3]:
taxi = pd.read_csv("taxi_little.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
taxi.drop("Unnamed: 0", inplace=True, axis=1)

In [5]:
taxi.set_index("Unnamed: 0.1", inplace=True)

In [6]:
taxi.index.rename("T_LINK_ID","dd")

In [7]:
taxi_raw = taxi.copy()

In [9]:
taxi.drop(["Dest", "X_PART", "Y_PART"], axis=1, inplace =True)

In [10]:
taxi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000000 entries, T_146396 to T_149847
Data columns (total 10 columns):
Day        1000000 non-null int64
Time       1000000 non-null int64
Weather    1000000 non-null int64
CntOn      604887 non-null float64
CntOff     236656 non-null float64
CntEmp     394139 non-null float64
X_MAX      1000000 non-null float64
Y_MAX      1000000 non-null float64
X_MIN      1000000 non-null float64
Y_MIN      1000000 non-null float64
dtypes: float64(7), int64(3)
memory usage: 83.9+ MB


In [11]:
a=taxi.combine_first(taxi)

In [12]:
tlqkf = taxi.drop_duplicates(["X_MAX", "Y_MAX"])
# 일단 이거 쓰면 순수 좌표만 뽑을 수 있음

In [13]:
a= tlqkf.X_MAX.to_list()

In [14]:
_list=list()

In [15]:
_list.append(a)

In [16]:
_list[0][1]

127.0300383738

In [17]:
b= tlqkf.Y_MAX.to_list()

In [18]:
_list.append(b)

In [19]:
_list[0][0], _list[1][0]

(127.0299311759, 37.6088426369)

In [55]:
m = folium.Map(["37.6088426369","127.0299311759"])

In [21]:
folium.Marker([_list[0][0], _list[1][0]],icon = folium.Icon(icon="cloud"))

In [22]:
for i in range(400):
    folium.Marker([str(_list[1][i]),str(_list[0][i])],icon = folium.Icon(icon="cloud", popup=i)).add_to(m)

In [23]:
folium.Marker([_list[0][100],_list[1][100]],icon = folium.Icon(icon="cloud")).add_to(m)

In [24]:
folium.Marker(["37.607151417","127.06727037549999"],icon = folium.Icon(icon="cloud", popup="hi")).add_to(m)

In [25]:
str(_list[1][400])=="127.06727037549999"

False

In [26]:
_list[1][400]

37.607151417

In [27]:
m

In [28]:
_list[0][1], _list[1][1]

(127.0300383738, 37.608753707199995)

In [29]:
_list[1][0], _list[1][1]

(37.6088426369, 37.608753707199995)

In [30]:
from folium.plugins import HeatMap 

data = ( np.random.normal(size=(100, 3)) * np.array([[1, 1, 1]]) + np.array([[48, 5, 1]]) ).tolist()

In [56]:
data=list()

In [57]:
for i in range(len(_list[0])):
    data.append(np.array((_list[1][i], _list[0][i])))

In [58]:
data

[array([ 37.60884264, 127.02993118]),
 array([ 37.60875371, 127.03003837]),
 array([ 37.60722127, 127.03121215]),
 array([ 37.59777342, 127.04242174]),
 array([ 37.59789324, 127.04242826]),
 array([ 37.60405389, 127.03187406]),
 array([ 37.61493936, 127.05468574]),
 array([ 37.61599136, 127.05548197]),
 array([ 37.61690193, 127.05656184]),
 array([ 37.61746884, 127.05043834]),
 array([ 37.61831392, 127.05185942]),
 array([ 37.6190058 , 127.05292302]),
 array([ 37.61970975, 127.05397704]),
 array([ 37.61693478, 127.05654744]),
 array([ 37.61604342, 127.05545906]),
 array([ 37.58937579, 127.0196766 ]),
 array([ 37.58528232, 127.0198368 ]),
 array([ 37.59038257, 127.01978137]),
 array([ 37.59135498, 127.0198944 ]),
 array([ 37.58944266, 127.01962548]),
 array([ 37.59138855, 127.01986272]),
 array([ 37.59093182, 127.01840231]),
 array([ 37.58533398, 127.01995488]),
 array([ 37.58587812, 127.0211094 ]),
 array([ 37.58579568, 127.02063852]),
 array([ 37.5859044 , 127.02142848]),
 array([ 37.

In [81]:
m = folium.Map(["37.6088426369","127.0299311759"])

In [82]:
HeatMap(data, blur=10, radius=10,max_zoom=100).add_to(m)

In [99]:
m

In [38]:
tt= pd.read_csv("taxi_little.csv")

In [39]:
tt.drop("Unnamed: 0", axis=1, inplace =True)

In [40]:
hi = list()

In [41]:
tt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 14 columns):
Unnamed: 0.1    1000000 non-null object
Day             1000000 non-null int64
Time            1000000 non-null int64
Weather         1000000 non-null int64
Dest            604887 non-null object
CntOn           604887 non-null float64
CntOff          236656 non-null float64
CntEmp          394139 non-null float64
X_MAX           1000000 non-null float64
Y_MAX           1000000 non-null float64
X_MIN           1000000 non-null float64
Y_MIN           1000000 non-null float64
X_PART          1000000 non-null object
Y_PART          1000000 non-null object
dtypes: float64(7), int64(3), object(4)
memory usage: 106.8+ MB


In [42]:
hi = [np.array(tt.Unnamed: 0.1
              )]

SyntaxError: invalid syntax (<ipython-input-42-b6843b455935>, line 1)

In [84]:
tt.rename(columns = {'Unnamed: 0.1': 'T_LINK'}, inplace =True)

In [103]:
hi= [np.array(tt.T_LINK),np.array(tt.Day), np.array(tt.Time), 
     np.array(tt.CntOn), np.array(tt.CntOff), np.array(tt.CntEmp), 
     np.array(tt.X_MAX), np.array(tt.Y_MAX)]

In [87]:
tt=tt.fillna(0)

In [88]:
len(tt)

1000000

In [105]:
hi[3][0]+hi[4][0]+hi[5][0]

321.0

In [195]:
name = list()

def tapseung(time, day=1):
    _sum =0
    i=0
    for i in range(999999):
        if hi[2][i]!=hi[2][i+1]or hi[0][i] !=hi[0][i+1] or hi[1][i]!=hi[1][i+1]:
            name.append([{hi[0][i]:_sum},{'Day':hi[1][i]},{"Time":hi[2][i]},{'i':i}, {"X_MAX":hi[6][i]},{"Y_MAX":hi[7][i]}])
            _sum = 0

        if hi[0][i] ==hi[0][i+1] and hi[1][i]==day and hi[2][i]==time:
            _sum +=(hi[3][i]+hi[4][i]+hi[5][i])
    return _sum

In [428]:
def tapseung(time, day):
    _sum =0
    i=0
    for i in range(999999):
        if time == hi[2][i] and day == hi[1][i]:
            if hi[2][i]!=hi[2][i+1] or hi[0][i] !=hi[0][i+1] or hi[1][i]!=hi[1][i+1]:
                name.append([hi[0][i],_sum,hi[1][i],hi[2][i], hi[6][i],hi[7][i]])
#                 name.append([{hi[0][i]:_sum}, {"X_MAX":hi[6][i]},{"Y_MAX":hi[7][i]}])
                _sum=0

            _sum +=(hi[3][i]+hi[4][i]+hi[5][i])
    return _sum

In [431]:
tapseung(0,1)

1.0

In [427]:
name = list()

In [430]:
len(name)

0

In [239]:
len(name)

136376

In [265]:
name[0][1]["Day"]

1

In [432]:
name

[['T_146396', 2488.0, 1, 0, 127.0299311759, 37.6088426369],
 ['T_146397', 1557.0, 1, 0, 127.0300383738, 37.608753707199995],
 ['T_146398', 2038.0, 1, 0, 127.0312121491, 37.6072212719],
 ['T_146399', 74.0, 1, 0, 127.04242173819999, 37.597773421],
 ['T_146400', 71.0, 1, 0, 127.04242825959999, 37.5978932434],
 ['T_146407', 649.0, 1, 0, 127.03187406209999, 37.604053889],
 ['T_146408', 686.0, 1, 0, 127.05468573879999, 37.6149393569],
 ['T_146409', 675.0, 1, 0, 127.0554819707, 37.6159913576],
 ['T_146410', 695.0, 1, 0, 127.0565618396, 37.6169019297],
 ['T_146411', 481.0, 1, 0, 127.0504383362, 37.6174688415],
 ['T_146412', 299.0, 1, 0, 127.0518594184, 37.6183139172],
 ['T_146413', 227.0, 1, 0, 127.0529230249, 37.6190057992],
 ['T_146414', 244.0, 1, 0, 127.05397703979999, 37.6197097492],
 ['T_146419', 476.0, 1, 0, 127.05654744, 37.616934778499996],
 ['T_146420', 492.0, 1, 0, 127.05545906190001, 37.6160434248],
 ['T_148792', 128.0, 1, 0, 127.0196766002, 37.5893757886],
 ['T_148794', 1249.0, 1, 

AttributeError: 'list' object has no attribute 'to_csv'

In [420]:
_taxi = pd.DataFrame(name)

In [421]:
_taxi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 4 columns):
0    407 non-null float64
1    407 non-null object
2    407 non-null float64
3    407 non-null float64
dtypes: float64(3), object(1)
memory usage: 12.8+ KB


In [434]:
_taxi.to_csv("test.csv")

In [347]:
m = folium.Map(("37.605955","127.062066"))

In [284]:
for i in range(len(name)):
    data.append(name[0][1])

In [307]:
str(name[i][2])
i=0

In [ ]:
data.append

In [316]:
for i in range(len(name)):
    HeatMap([str(name[i][3]), str(name[i][2])]).add_to(m)
#     folium.Marker([str(name[i][3]), str(name[i][2])],icon = folium.Icon(icon="cloud", popup=i)).add_to(m)
#     folium.Marker([str(_list[1][i]),str(_list[0][i])],icon = folium.Icon(icon="cloud", popup=i)).add_to(m)
#     HeatMap([str(name[i][2]), str(name[i][3])], blur=10, radius=10,max_zoom=100).add_to(m)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [327]:
for i in range(len(name)):
    data.append(np.array((name[i][3], name[i][2])))

In [328]:
data

[array([ 37.60884264, 127.02993118]),
 array([ 37.60875371, 127.03003837]),
 array([ 37.60722127, 127.03121215]),
 array([ 37.59777342, 127.04242174]),
 array([ 37.59789324, 127.04242826]),
 array([ 37.60405389, 127.03187406]),
 array([ 37.61493936, 127.05468574]),
 array([ 37.61599136, 127.05548197]),
 array([ 37.61690193, 127.05656184]),
 array([ 37.61746884, 127.05043834]),
 array([ 37.61831392, 127.05185942]),
 array([ 37.6190058 , 127.05292302]),
 array([ 37.61970975, 127.05397704]),
 array([ 37.61693478, 127.05654744]),
 array([ 37.61604342, 127.05545906]),
 array([ 37.58937579, 127.0196766 ]),
 array([ 37.58528232, 127.0198368 ]),
 array([ 37.59038257, 127.01978137]),
 array([ 37.59135498, 127.0198944 ]),
 array([ 37.58944266, 127.01962548]),
 array([ 37.59138855, 127.01986272]),
 array([ 37.59093182, 127.01840231]),
 array([ 37.58533398, 127.01995488]),
 array([ 37.58587812, 127.0211094 ]),
 array([ 37.58579568, 127.02063852]),
 array([ 37.5859044 , 127.02142848]),
 array([ 37.

In [344]:
HeatMap(data,name = "what", blur=10, radius=10,max_zoom=100).add_to(m)

In [355]:
name[0][0]

2488.0

In [356]:
del(popups)

In [361]:
popups = [str(name[i][0]) for i in range(len(name))]

In [362]:
popups

['2488.0',
 '1557.0',
 '2038.0',
 '74.0',
 '71.0',
 '649.0',
 '686.0',
 '675.0',
 '695.0',
 '481.0',
 '299.0',
 '227.0',
 '244.0',
 '476.0',
 '492.0',
 '128.0',
 '1249.0',
 '154.0',
 '250.0',
 '1015.0',
 '93.0',
 '93.0',
 '642.0',
 '323.0',
 '1219.0',
 '64.0',
 '107.0',
 '455.0',
 '167.0',
 '79.0',
 '4330.0',
 '178.0',
 '670.0',
 '303.0',
 '209.0',
 '451.0',
 '497.0',
 '623.0',
 '506.0',
 '559.0',
 '521.0',
 '1465.0',
 '1598.0',
 '661.0',
 '420.0',
 '2148.0',
 '1986.0',
 '1105.0',
 '1684.0',
 '1667.0',
 '1734.0',
 '731.0',
 '671.0',
 '960.0',
 '915.0',
 '611.0',
 '729.0',
 '567.0',
 '401.0',
 '189.0',
 '81.0',
 '106.0',
 '262.0',
 '180.0',
 '150.0',
 '122.0',
 '139.0',
 '136.0',
 '154.0',
 '317.0',
 '510.0',
 '76.0',
 '515.0',
 '524.0',
 '34.0',
 '29.0',
 '23.0',
 '3.0',
 '5.0',
 '10.0',
 '13.0',
 '21.0',
 '14.0',
 '73.0',
 '108.0',
 '60.0',
 '61.0',
 '6.0',
 '115.0',
 '169.0',
 '64.0',
 '65.0',
 '36.0',
 '7.0',
 '1074.0',
 '1177.0',
 '208.0',
 '68.0',
 '309.0',
 '263.0',
 '352.0',
 '4

In [363]:
plugins.MarkerCluster(data, popups=popups).add_to(m)

In [364]:
folium.

In [398]:
m1= folium.Map(("37.61850888", "127.04365106"))

In [391]:
HeatMap(data, radius=15).add_to(m1) # default =25

In [397]:
name[0][0]

2488.0

In [409]:
for i in range(len(name)):
#     data=(np.array((name[i][3], name[i][2])))
#     radius1 = name[i][0]/100
    HeatMap(np.array((name[i][3], name[i][2]))).add_to(m1)

IndexError: invalid index to scalar variable.

In [403]:
radius1
, radius=str(radius1)

8.0